language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests --enable-coverage -v2 -f dev
 - cabal build
 - travis_wait 45 cabal test --show-details=always
 - cabal sdist
 - cabal haddock | grep "100%" | wc -l | grep "4"

after_script:
 - cabal install hpc-coveralls
 - export PATH=~/.cabal/bin:$PATH
 - hpc-coveralls --coverage-mode=StrictlyFullLines
                 --exclude-dir=tests
                 tests

notifications:
  email: false
